### ISSUE TITLE
How do i actually use it?

### ISSUE THREAD

**Issue by Oce4nM4n** [LeonardSSH/vscord#10]
I can't see how to actually use it

**Comment by JackCrispy** [comment]
Install the extension and it will automatically work whenever you open a file.

**Comment by sanketsaagar** [comment]
Hey, @JackCrispy is it works with any particular file? Or works normally? Because after installing the extension, it's not working

**Comment by LeonardSSH** [comment]
@sanketsaagar what do you mean it's not working? Any warnings/errors?

**Comment by theodugautier** [comment]
@sanketsaagar I don't have the info, but if you are on Linux, you have to install it from the official discord site and not with snap.
