### ISSUE TITLE
Feature - Detect all vscode windows open to check for activity 

### ISSUE THREAD

**Issue by nick22985** [leonardssh/vscord#102]
Check all vscode instances/windows if there is an activity in any of them or detect current focused one. At the moment if it gets attached to an idle window and u then open a new window it will use the old window and just say idle.

/ only uses the first window for the rpc

**Comment by xhayper** [comment]
i can't seem to tackle this

**Comment by xhayper** [comment]
https://github.com/leonardssh/vscord/tree/feat/controller

**Comment by xhayper** [comment]
for context, `visibleTextEditors` return empty arrayu when that happened

**Comment by nick22985** [comment]
This can be closed as it is related to discord that is causing this when multiple activity windows are open there are multiple presences but discord doesn't choose the active one / the one that is changing
