### ISSUE TITLE
Add support for a few languages

### ISSUE THREAD

**Issue by xhxnna** [leonardssh/vscord#103]
Could you add support for:
- [x] Hare: https://harelang.org (`.ha`)
- [x] C3: https://c3-lang.org (`.c3`)
- [ ] Fortran: https://fortran-lang.org (`.f90`, etc)
- [x] Odin: https://odin-lang.org (`.odin`)

Thanks!

**Comment by xhayper** [comment]
Fortan PR exist, but i asked for the author to change the icon. #79 

C3... i don't know where to find the icon.

Hare.... does it have a rabbit or goat mascot.......?

**Comment by xhxnna** [comment]
The C3 logo is just the text C3, so could probably just throw it up in Photoshop and call it a day lolAs for hare, the mascot is a rabbit.

**Comment by xhayper** [comment]
gotcha, i am very bad at photo editing sooo if i can't do it... i might need your help, also i do not know what font leonardssh use for text

**Comment by xhayper** [comment]
Here's my best attempt at making C3 logo
![image](https://user-images.githubusercontent.com/46065349/196901357-b3e91220-a9a1-474b-9e01-fdf84e8ddc29.png)

**Comment by xhayper** [comment]
agh, the font is wrong, give me a moment

**Comment by xhayper** [comment]
C3 is implemented in f819fa2

**Comment by xhxnna** [comment]
Looks fine haha

**Comment by xhayper** [comment]
i only add C3 for now

**Comment by xhxnna** [comment]
Would something like this work for hare?
![hare](https://user-images.githubusercontent.com/46457601/196941974-8940c1a3-ade7-448e-9050-d2d001273309.png)

**Comment by xhayper** [comment]
hmmm, that looks nice, raise a PR for it please :D

**Comment by xhayper** [comment]
https://github.com/leonardssh/vscord/blob/main/assets/icons/README.md

**Comment by xhayper** [comment]
make sure it's 1024x1024 btw

**Comment by xhayper** [comment]
and don't worry about having to wait for next release, the image will work right away!
