### ISSUE TITLE
[workspace] To always look through ignore workspaces when using it for variables

### ISSUE THREAD

**Issue by nick22985** [leonardssh/vscord#135]
When using `{workspace}` for the idle state it does not filter out and replace the entire text with the `vscord.ignore.workspacesText` when a string matches

**Comment by xhayper** [comment]
Could you elaborate a bit more? I am a little bit confused,

**Comment by nick22985** [comment]
Say you put {workspace} in the idle text. It doesn't filter it https://gyazo.com/f0f9cfd9f01b82f753ff15891c73a13b

**Comment by xhayper** [comment]
Ah, an oversight, I will look into this.

**Comment by xhayper** [comment]
i though this would be an easy fix, i don't know what cause this because it use the same replace function as everything else so it should filter it out...? what??????

**Comment by nick22985** [comment]
Yea it is weird thought the regex would also solve this but didnt

**Comment by xhayper** [comment]
i am super confused on how to fix this

**Comment by nick22985** [comment]
Closing as #146 fixes this also
