### ISSUE TITLE
vscord still showing that I'm idling after setting it not to

### ISSUE THREAD

**Issue by dooder-codes** [leonardssh/vscord#136]
Here are my settings in alphabetical order:

![image](https://user-images.githubusercontent.com/40189403/199990407-b8ecde76-467a-4112-a47e-0e6211b9ac6b.png)

**Comment by xhayper** [comment]
there is some misunderstanding, the idle check settings is responsible to checking if you are idle after the `timeout` amount, if you disable that, you won't get idle after being inactive for `timeout` amount.

**Comment by dooder-codes** [comment]
@xhayper `"idle.check"` set to false still idles me after idle timeout.

**Comment by xhayper** [comment]
This is weird.

**Comment by xhayper** [comment]
Figured out the root of the problem, pushing a fix out.

**Comment by dooder-codes** [comment]
@xhayper Thank you very much! Much appreciated.
