### ISSUE TITLE
[Feature-Request] Custom "Elapsed Time" - Layout

### ISSUE THREAD

**Issue by Hedrauta** [leonardssh/vscord#138]
Is it possible to set an own Timer-"statement" like the problem one? --> `vscord.status.problems.text`

I do not even try to understand vscord to code that one for myself 
😉 but it's an awesome tool, and that little feature would finish the touch for someone like me 😏

![image](https://user-images.githubusercontent.com/20142298/200511426-2e4d850d-3c36-4810-945d-cff38de66fc2.png)
something funnier like: `Lifetime wasted: ` could fit here better 😜 

Sincere, Hed

**Comment by xhayper** [comment]
Updating the text every 1 second isnt a good idea..

**Comment by leonardssh** [comment]
Yeah.. at the moment I don't think we can do anything about it, until discord releases something official that we can use.
