### ISSUE TITLE
[feature-request]hide the host info when connect with remote-ssh extension

### ISSUE THREAD

**Issue by 26z1a** [leonardssh/vscord#139]
i'm coding on a remote server using [remote-ssh](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh). and i noticed my hostname(in my case my server's ip address) is showing on my discord Rich Presence.

so maybe we can hide the remote server infos somehow?

here's a screenshot of my discord Rich Presence:
![image](https://user-images.githubusercontent.com/15630912/200754428-71dd052b-56a9-4d11-9778-61cbf2ce4e8b.png)

**Comment by xhayper** [comment]
This is actually intended behaviour(comma) when you connect to workspace over ssh(comma) the namespace got set to exactly that(comma) here's a fix for that https://github.com/iCrawl/discord-vscode/issues/1617#issuecomment-1173038536

**Comment by nick22985** [comment]
Putting this here if I get time or someone wants to go implement it
```
let ipRegex = new RegExp("(\[SSH: \\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}])", "gs");
let ip = '[SSH: 192.168.1.1]'
let ipReplace = ip.replace(ipRegex, '');
```

**Comment by xhayper** [comment]
I am not sure how we gonna implement it because we would need to add the said regex to everything too each setting

**Comment by nick22985** [comment]
Yea maybe just having it for ssh for now.

Updated regex to match domains as well as it was only ips before

**Comment by xhayper** [comment]
that can cause an edge case where people would use `[]` in the folder name for organization

**Comment by nick22985** [comment]
Unless they do [SSH: folder name] it wont match

**Comment by xhayper** [comment]
Hmm... yeah wecan implement it... but it gonna be hacky for now since i am working on another projecyt and doesn't have time to add 20 more settings.

**Comment by xhayper** [comment]
Combing with an if statement to check if we are in remote with [this regex](https://regex101.com/r/mqS3Qh/1) and we should prob we good
