### ISSUE TITLE
[Feature] Add the ability for a user to have a completely custom button

### ISSUE THREAD

**Issue by nick22985** [leonardssh/vscord#144]
https://gyazo.com/84d86e15ee93a18ddabc4ac962645fe1
let the user add another button to the presence / allow full customization of this button.
- Ability to tell it all states online/idle etc. 
- Allow it to be enabled when user is working and disabled when the user is not.
- Allow a setting to do with buttons when there are ignore repo / organisation / folder. Should it maintenance the two buttons or should it go back to one

**Comment by xhayper** [comment]
gonna plan on hw to put the config and stuff, we need to have a condition where user is in a git project or not, it gonna be a real mess, we need better way to handle config for this.
