### ISSUE TITLE
Suggestion: Add 'View Repository' button

### ISSUE THREAD

**Issue by xLive** [LeonardSSH/vscord#15]
![image](https://user-images.githubusercontent.com/30420446/124282539-9d22bc80-db53-11eb-909e-822dde58fd26.png)

Sorry for many changing in the title, I misclicked enter while I'm typing xD

**Comment by LeonardSSH** [comment]
Feature implemented. update the extension and you will be able to enjoy it. https://github.com/LeonardSSH/vscord/commit/6311d183632353f22b9e193bbb8224c249d81d68
