### ISSUE TITLE
Implement Squirrel (.nut) support

### ISSUE THREAD

**Issue by b7lt** [leonardssh/vscord#161]
Hello (: 

Squirrel (file extension .nut ) is a language that is used for writing scripts and modifications for many popular games. 
An extensive list of examples can be found here: https://en.wikipedia.org/wiki/Squirrel_(programming_language)#Applications

I was wondering if it could be added to the list of supported languages 😄

**Comment by xhayper** [comment]
I am a big fan of the file extension xD.

**Comment by xhayper** [comment]
I can add the language to the list, ofc, but i dont be able to make the icon until i get home, since i only know how to make icons in paint.net and not other software like gimp, and i only have a mac machine with me xD.

**Comment by b7lt** [comment]
LOL haha no rush. thank you so much :)

**Comment by xhayper** [comment]
Now we just need the icon!

**Comment by Jsostmann** [comment]
Opened @xhayper @b7lt 
https://github.com/leonardssh/vscord/pull/186 for image support 😃
