### ISSUE TITLE
Troubles creating "View Repository" button

### ISSUE THREAD

**Issue by hyperupcall** [LeonardSSH/vscord#165]
Hi,

Coming from Crawl's extension because this one starts up in half the time (thanks!), and I'm having trouble enabling the "view repository" button.

I looked at the Feature Contributions, and I tried to set `vscord.status.buttons.button1.git.active.enabled` to `true`, since it seemed that it would do what I want, but that didn't do anything.

I also tried to add this config, to no avail:

```json
{
   "vscord.status.buttons.button1.active.enabled": true,
   "vscord.status.buttons.button1.active.label": "View Repository",
   "vscord.status.buttons.button1.active.url": "{git_url}",
}
```

So I'm asking, how would I go about doing this, since it seems this feature is suported?

Maybe this issue is related to #151. For me, a more intuitive system would have a configuration like so:

```json
"vscode.status.buttonActive": "myButtonA", 
"vscode.status.buttons": {
  "myButtonA": { ... },
  "myButtonB": { ... },
}
```

That way, an arbitrary amount of buttons can be added without cluttering the "Feature Contributions" extension tab. It would also be really simple to have have multiple builtin buttons and then be able to specify through `buttonActive`. Maybe you can make the `image` parts of the config object-based too Of course this would have to be documented somewhere...

**Comment by xhayper** [comment]
why did we never think of that @leonardssh @nick22985 XD

it might also be a bug too, i will have to talk with two contributors I mentioned first.

**Comment by nick22985** [comment]
That is a better way of formatting it xD and hanling lol

**Comment by xhayper** [comment]
nick, can try it and see if the settings menu show "Edit in settings.json" or easy to edit gui

**Comment by nick22985** [comment]
Dont have much time atm will get to this when I can unless someone else wants to

**Comment by el-ang** [comment]
man.. got the same problem, but this issue closed quickly. Now i hope i appeared outta nowhere so i can contribute. And i think i know why its realy messy tho 😕
