### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SamuuX** [leonardssh/vscord#166]
- Issue Type: `Performance`
- Extension Name: `vscord`
- Extension Version: `5.0.18`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.74.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Usuario/AppData/Local/Temp/LeonardSSH.vscord-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by xhayper** [comment]
You didn't attach it correctly...
