### ISSUE TITLE
The variable {currentline} shows: 1 

### ISSUE THREAD

**Issue by GHKazza** [LeonardSSH/vscord#17]
The variable {currentline} shows the value: 1 instead of the current line in which I am editing, this happens with all the files that I have been able to test: .JS - .HTML - .JSON and .MD

Example:

File: test.js 
Editing: Line 5

![image](https://user-images.githubusercontent.com/45432294/128655844-9ec91197-3e87-476b-8183-1781cede09f5.png)

Discord Rich Presence showing "Line: {currentline}" = "Line: 1" 

![image](https://user-images.githubusercontent.com/45432294/128655644-06c7f706-be55-4015-b25d-c52dd462b949.png)

Settings:

![image](https://user-images.githubusercontent.com/45432294/128655874-bbd5c5f2-13a2-49ea-a63d-25597bfe17dc.png)

**Comment by LeonardSSH** [comment]
The problem should be fixed in the newly released version, please upgrade to the extension and let me know if the problem is fixed.

**Comment by GHKazza** [comment]
> The problem should be fixed in the newly released version, please upgrade to the extension and let me know if the problem is fixed.

It's fixed! Thank you so much!

**Comment by GHKazza** [comment]
> The problem should be fixed in the newly released version, please upgrade to the extension and let me know if the problem is fixed.

It's fixed! Thank you so much!
