### ISSUE TITLE
command vscord.enable/disable not found

### ISSUE THREAD

**Issue by Marc-Harony** [leonardssh/vscord#170]
Hello 👋🏻 
First of all, thank you for this extension 🙏🏻 
I have a problem though. When I start VSCode, the extension does not start automatically, I have to start it manually, and when I do, I get an error :
`vscord.enable not found`
When I uninstall and reinstall the extension, it works again until I restart VSCode..
Do you have any idea how to fix this problem?
Do you need more information?
Thanks for any help you can give me.

edit: I'm running VSCode on Windows 11

**Comment by nick22985** [comment]
This is related to .git not loading correctly most likely
https://github.com/leonardssh/vscord/commit/98db028af5da06ef29f0926883bfae1d4e1b5643

I suspect you can confirm by going help -> toggle dev tools and looking for the vscord error.

**Comment by Marc-Harony** [comment]
Yes, that looks like it is the same error:
`Activating extension 'LeonardSSH.vscord' failed: Extension 'vscode.git' is not known or not activated.
$onExtensionActivationError @ workbench.desktop.main.js:2153
workbench.desktop.main.js:616  WARN UNRESPONSIVE extension`
I am currently using what appears to be the latest version of the extension from the VSCode store.

**Comment by Davilarek** [comment]
any update on this?

**Comment by xhayper** [comment]
No progress on this, it happened randomly and is hardly re-producable

**Comment by C-o-d-e-C-o-w-b-o-y** [comment]
I still get this most of the time using Cursor / macOS 15.6.1

Only sometimes fixes after I restart whole computer multiple times

<img width="272" height="245" alt="Image" src="https://github.com/user-attachments/assets/cc1bdbc5-7cba-4b22-921e-0dffd61cb271" />
