### ISSUE TITLE
Inactive "View Repository" button won`t work?

### ISSUE THREAD

**Issue by Jannissss** [LeonardSSH/vscord#18]
Hello, I wanted to set the URL of the inactive "View Repository" button to the following https://www.youtube.com/watch?v=dQw4w9WgXcQ. But when I enter that in the line for the URL for the inactive "View Repository" Button and click it in the discord status, nothing happens.

I've also tried to paste the link from the share option from Youtube, but it didn't worked either.

![image](https://user-images.githubusercontent.com/86200359/129757149-639dbd45-c89c-43d5-9b16-6fbde510e847.png)

**Comment by LeonardSSH** [comment]
Hey, that custom button only appears when the workspace you are working in doesn't have a github repo (**.git** folder)

You must also specify which label you want the button to have and which link.
```json
"rpc.buttonInactiveLabel": "Click Me!",
"rpc.buttonInactiveUrl": "YOUR LINK HERE"
```

**Comment by Jannissss** [comment]
> Hey, that custom button only appears when the workspace you are working in doesn't have a github repo (**.git** folder)
> 
> You must also specify which label you want the button to have and which link.
> ```json
> "rpc.buttonInactiveLabel": "Click Me!",
> "rpc.buttonInactiveUrl": "YOUR LINK HERE"
> ```

The file isn't in a GitHub repo, and I also specified the label in the GUI Settings.

**Comment by LeonardSSH** [comment]
See https://github.com/LeonardSSH/vscord/issues/20#issuecomment-901091316
