### ISSUE TITLE
remove "view repository"

### ISSUE THREAD

**Issue by jaocarli** [leonardssh/vscord#187]
Hello guys! recently I've been having some problems with the repositories I've been using at work, even though they are private. Is there any way to remove the "View Repository" button in the extension settings?

**Comment by xhayper** [comment]
You can disable it in settings!

https://github.com/leonardssh/vscord/blob/main/package.json#L467

**Comment by xhayper** [comment]
The section for `View Repository` config has been reworked and it should be much easier for you to customize the behaviour!
