### ISSUE TITLE
Couldn't connect to Discord via RPC: RPC_CONNECTION_TIMEOUT

### ISSUE THREAD

**Issue by authorless** [leonardssh/vscord#194]
I ran into a problem where RPC can't get a connection.
I've already tried all the ways. I waited 10 minutes after creating the bot; entered the user id (my own); entered the application id and all in vain. Help me please...

**Comment by xhayper** [comment]
Restart your discord, see if it fix the issue

**Comment by QuentiumYT** [comment]
Also just a question, is it possible to disable this annoying notification if we don't want to start discord when coding? Would be amazing to just add an option to silent these (keeping the "reconnect to discord gateway" in the status bar)

**Comment by jahirfiquitiva** [comment]
I agree with @QuentiumYT ... I requested that option some time ago #16 ... they "fixed" it for a while, but it's showing up again.

Besides, I don't always want Discord open, so it would be nice to be able to hide this notification.

**Comment by NielsNL1** [comment]
> And also gives an error: "Failed to reconnect to Discord Gateway"
i had the smae problem and did this, it worked for me.

**Comment by neptunecorsiva** [comment]
> > And also gives an error: "Failed to reconnect to Discord Gateway"
> 
> i had the same problem and did this, it worked for me.

did what exactly?

**Comment by NielsNL1** [comment]
> > > And also gives an error: "Failed to reconnect to Discord Gateway"
> > 
> > 
> > i had the same problem and did this, it worked for me.
> 
> did what exactly?

Restart discord

**Comment by sh1nano** [comment]
you can restart the extension in the vscode with already running discord, and it should work. just tried it right now and it works ;)

**Comment by mkukiro** [comment]
I have the same problem and all of the solutions didn't work

**Comment by xhayper** [comment]
Gosh, this issue came to haunt me everyday,

RPC_CONNECTION_TIMEOUT happeneds when:
A. Discord decided to stop respond to your request because you open too much RPC connection
B. You don't have discord open
C. IPC path is incorrect
D. Can't connect to IPC path

There's so many factor....

**Comment by xhayper** [comment]
I don't know how to tackle any of these problems at all

**Comment by xhayper** [comment]
Good idea

**Comment by mkukiro** [comment]
Any updates on this?

**Comment by xhayper** [comment]
Alright, re-visiting this old issue.

If you are on linux, and are using snap / flatpak version of vscode, please switch to the official version downloaded from the site itself.

If you are on windows, update the extension to the latest version

If you still get this bug, feels free to open a new issue

**Comment by xhayper** [comment]
For the notification part, i will work on it tomorrow, sorry for not working on it
