### ISSUE TITLE
Repository button disappears on 5.1.4 (regression from 5.1.3)

### ISSUE THREAD

**Issue by Willy-JL** [leonardssh/vscord#197]
I have an issue on 5.1.4, which is not present on 5.1.3.

On 5.1.3, with the default configuration, the first "View Repository" button is shown when a repo is detected, and remains shown when idle or when not in a file. On 5.1.4 instead I've had many issues with this behavior, like the button disappearing when idle or not in a file, or the link being incorrect and pointing to a rick roll, and if I manually override the rick roll link, it fails to parse the `{git_url}` and says invalid URL for button 1. I would assume this is due to a logic mistake, where the git repo context is skipped if idle state is detected.

I'm also having another logic issue, which is kind of expected and behaving correctly, but makes little sense. I included file details like filename and line count in the state text (second line) to also show when idle, and set the not in file text correctly.When I go idle on a file, I keep seeing the correct details, and if I'm not in a file that also shows correctly; going idle when not in a file however, will try to use the idle text instead of the not in a file text, which is correct logic wise, but this means that the file information string is used and leaves details empty (in my case I see ` ( lines)` due to missing filename and line count). I see 2 possible solutions: using the "not in file" text when "idle and not in file", or adding an additional config entry for "idle and not in file" state.

**Comment by nick22985** [comment]
I assume what has happened is the config has changed the defaults for some reason or another. This is fully configurable tho.

Nothing logically should have changed regarding anything to do with the presence the only changes in 5.1.3 and 5.1.4 was adding debug to the buttons.

https://github.com/leonardssh/vscord/compare/v5.1.3...v5.1.4

**Comment by Willy-JL** [comment]
Dont know what to tell you. Matter of fact is that the first button is VERY broken on 5.1.4. Maybe the wrong files were pushed to the market place and what is on there does not reflect the source code on here. Either way, on 5.1.4 the first button completely ignores the git repository, while 5.1.3 works flawlessly in that regard. I just tried again to confirm, and used the same hardcoded custom settings just to be sure.

**Comment by Willy-JL** [comment]
Yup. Just verified compiling from source, with 45fa86b5d3168215824608f028908894ec36d4f7 all works as expected, while on 5e4bb14110049fbeb290a736e771ad26b9c1b0a0 (parent commit) I get the issue with button missing

**Comment by nick22985** [comment]
What is the state that is left out I don't think we want to return inactive if the state is actually undefined. State should not be undefined either if the state shouldn't be shown due to an exemption or something else that has gone wrong.

Can u post the config you have set I do not have a problem with what you are describing / cant recreate it in the live version?


This is my exact config for buttons
```
	"vscord.status.buttons": {
		"button1": {
			"enabled": true,
			"preset": "test",
			"active": {
				"label": "Check Out My Github",
				"url": "https://github.com/nick22985",
				"enabled": true
			},
			"idle": {
				"label": "Check Out My Github",
				"url": "https://github.com/nick22985",
				"enabled": true
			},
			"inactive": {
				"label": "Check Out My Github",
				"url": "https://github.com/nick22985",
				"enabled": true
			},
			"git": {
				"enabled": true,
				"idle": {
					"label": " View Repository ",
					"url": "{git_url}",
					"enabled": true
				},
				"active": {
					"label": "View Repository",
					"url": "{git_url}",
					"enabled": true
				},
				"inactive": {
					"label": "View Repository",
					"url": "{git_url}",
					"enabled": true
				}
			}
		},
		"button2": {
			"enabled": true,
			"active": {
				"label": "Check Out My Website",
				"url": "https://nick22985.com",
				"enabled": true
			},
			"idle": {
				"label": "Check Out My Website",
				"url": "https://nick22985.com",
				"enabled": true
			},
			"inactive": {
				"label": "Check Out My Website",
				"url": "https://nick22985.com",
				"enabled": true
			},
			"git": {
				"enabled": true,
				"idle": {
					"label": "Check Out My Github",
					"url": "https://github.com/nick22985",
					"enabled": true
				},
				"active": {
					"label": "Check Out My Github",
					"url": "https://github.com/nick22985",
					"enabled": true
				},
				"inactive": {
					"label": "Check Out My Github",
					"url": "https://github.com/nick22985",
					"enabled": true
				}
			}
		}
	},
```
