### ISSUE TITLE
View Repository button doesn't show up

### ISSUE THREAD

**Issue by Nalin-2005** [LeonardSSH/vscord#20]
I think the title is enough... The "View Repository" button doesn't show up on my discord.
Here is what shows:
![image](https://user-images.githubusercontent.com/54469875/129847214-8deaf244-c3a9-4287-8c77-595c50a53aa5.png)
No button below that. IDK what's the issue, the project is a git repository, and there also exists a remote named `origin`

One more suspicious thing is that i cannot find any settings named `rpc.buttonEnabled` in my settings.json, neither such a setting exists in the settings tab. Although this setting's value is set to True by default, still there is no affect. My VSCode is also of the latest version.

**Comment by LeonardSSH** [comment]
Hey, did you try a reinstall of the extension? Often, a reinstall is welcome, and in most cases, solves the problem.

**Comment by Nalin-2005** [comment]
Yes, re-installing the extension worked, but partially. Now it shows the button, but the button does not do anything. I keep clicking on it again and again and the only thing it does is show a ripple effect. Nothing else.

**Comment by LeonardSSH** [comment]
Yeah... I've noticed that, you can't press the button yourself, only others can press it, and you in turn can press it on others, but not on yourself.

**Comment by LeonardSSH** [comment]
I really have no idea why, I've noticed the same problem with other extensions on the market. 

¯\_(ツ)_/¯

**Comment by Nalin-2005** [comment]
Well, anyway, thanks for guiding me, i'm closing the issue now.
