### ISSUE TITLE
HEEx icon appears to be broken

### ISSUE THREAD

**Issue by Pistrie** [leonardssh/vscord#202]
Here is a screenshot of the problem:
![image](https://user-images.githubusercontent.com/39904003/229563363-7e0f66b4-4e55-4dd3-b8ec-7d732d757b96.png)

**Comment by xhayper** [comment]
It works fine for me...?
![image](https://user-images.githubusercontent.com/46065349/229566955-f426a77a-68a2-4911-8cfd-575ebcb97b03.png)

could you go to https://discord.com/channels/@me and inspect the rpc icon to see what url it is using?

**Comment by Pistrie** [comment]
Hm, the browser version of Discord does display it, but the Flatpak version doesn't. I'd tell you what the broken link points to, but they disabled the dev console

**Comment by xhayper** [comment]
probably the latter
