### ISSUE TITLE
[Arch Linux] No Discord RPC?

### ISSUE THREAD

**Issue by Mezo-hx** [leonardssh/vscord#207]
The RPC Doesn't seem to be working at all, I downloaded discord from my package manager (pacman) and not flatpak, so idrk why it's not working

**Comment by nick22985** [comment]
Do you have any privacy settings on discord? Also is vscode flatpack. I use to use arch and it was working for me then. Is there any debug logs / what is the error you experiences?

**Comment by Mezo-hx** [comment]
> Do you have any privacy settings on discord? Also is vscode flatpack. I use to use arch and it was working for me then. Is there any debug logs / what is the error you experiences?

vscode isn't flatpak to the extent of my knowledge, it was also downloaded from the AUR. And I do have some privacy settings on discord.

I'm not sure about the debug logs... But the error I'm getting is that  the rpc isn't working, it says "connected to Discord", but I'm truly not seeing the RPC that it's supposed to show.

**Comment by xhayper** [comment]
Please check if you are using a non snap / flatpack version of VSCode, this extension does not work with snap / flatpak version of VSCode, feels free to re-open this issue if this is not the cause, i would love to help you out with this bug
