### ISSUE TITLE
Disable notification that Discord couldn't be connected

### ISSUE THREAD

**Issue by haselkern** [LeonardSSH/vscord#21]
I like this extension but I tend to often switch projects in vscode while Discord is not open. This results in the following error notification:

```
Couldn't connect to Discord via RPC: Error: Could not connect
```

I can easily check the status of this extension in the status bar, if I want to know whether it is connected or not. Having this notification pop up all the time is quite annoying.

Would it be possible to have a toggle in the settings to turn this notification off?

**Comment by LeonardSSH** [comment]
I'll implement an option to disable notifications ASAP.

**Comment by LeonardSSH** [comment]
https://github.com/LeonardSSH/vscord/commit/152ac93e7d2d96840b4293e3d497480f6bdc070e
