### ISSUE TITLE
Cant change the custom name

### ISSUE THREAD

**Issue by EXPANDEDdong** [leonardssh/vscord#210]
no matter where i look i cant find any setting that changes the custom IDE name its just locked to code and doesnt work with any other name

**Comment by xhayper** [comment]
You need to supply your own Application Id.

**Comment by 0x5b62656e5d** [comment]
How do I supply my own application ID and what is that?

**Comment by EDM115** [comment]
@0x5b62656e5d go on https://discord.com/developers/applications, create a new App, its name will be the displayed name and its Application ID will be the one you have to set in settings
