### ISSUE TITLE
[Language Request] Odin

### ISSUE THREAD

**Issue by xpyxel** [LeonardSSH/vscord#22]
Was looking at your extension as it seems [iCrawl's](https://github.com/iCrawl/discord-vscode) extension hasn't been receiving updates besides dependabot dependency upgrades, a bit ago on theirs i requested a language, specifically [Odin](https://github.com/iCrawl/discord-vscode/issues/1077) to be added, but it was never looked into, assuming this extension is more updated is it possible this could be added?

**Comment by xpyxel** [comment]
Also i noticed when editing a zig file the large image was broken, just a heads up.

**Comment by LeonardSSH** [comment]
OK, see you in Valhalla. 😁

ON-TOPIC: Of course, I'll do support for Odin ASAP.

**Comment by xpyxel** [comment]
> OK, see you in Valhalla. grin
> 
> ON-TOPIC: Of course, I'll do support for Odin ASAP.

If you don't mind, can I add you on Discord?

**Comment by LeonardSSH** [comment]
> > OK, see you in Valhalla. grin
> 
> > 
> 
> > ON-TOPIC: Of course, I'll do support for Odin ASAP.
> 
> 
> 
> If you don't mind, can I add you on Discord?
> 
> 
> 
> ON-TOPIC: Thanks!

Sure. Leonard#6666

**Comment by LeonardSSH** [comment]
Implemented. See https://github.com/LeonardSSH/vscord/commit/f08fa9cf1ea437e71e6d33294137a1aa374960d7.
