### ISSUE TITLE
RPC_COULD_NOT_CONNECT (Windows 11)

### ISSUE THREAD

**Issue by afifdevtest** [leonardssh/vscord#229]
I have issues with the extension cannot connect via RPC
![image](https://github.com/leonardssh/vscord/assets/87959424/58792f26-be54-48f5-ac2c-4b34d17a62e5)

My discord and vscode runs well, is there any suggestion ?

**Comment by xhayper** [comment]
47e554b18c4c311ac938be0076c08f6241cf3e63 should fix this
