### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MomoPi-Dark** [leonardssh/vscord#230]
- Issue Type: `Performance`
- Extension Name: `vscord`
- Extension Version: `5.1.14`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.80.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/USER/AppData/Local/Temp/LeonardSSH.vscord-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by xhayper** [comment]
you are meant to attach the file not send the file path
