### ISSUE TITLE
HTML Files.

### ISSUE THREAD

**Issue by DragonsRule10** [leonardssh/vscord#231]
Cant get the extension to show my HTML file in a GitHub repository.

**Comment by prechy123** [comment]
Use git....

Init git
git status
git commit -m "write whatever"
Git push origin master

Or
Simply just upload the file, by clicking add existing project when creating GitHub repository

**Comment by xhayper** [comment]
I dont think i understand what you are trying to say, like wdym by github repository? is it local or remote?

**Comment by DragonsRule10** [comment]
Yes, it's a remote repository. I was editing it in VSCode, but I saw that the html files don't show up in my rich presence, yet other files in my repository do, like js files.

**Comment by xhayper** [comment]
Thats weird, any error in the console?

**Comment by prechy123** [comment]
> I dont think i understand what you are trying to say, like wdym by github repository? is it local or remote?

Open on pc and follow this doc
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository

**Comment by prechy123** [comment]
> Yes, it's a remote repository. I was editing it in VSCode, but I saw that the html files don't show up in my rich presence, yet other files in my repository do, like js files.

It will...

**Comment by DragonsRule10** [comment]
> Thats weird, any error in the console?

Not that I know of, I'll check later.

**Comment by xhayper** [comment]
Need more info + reproduction step, feels free to re-open the issue!
