### ISSUE TITLE
Add support for the Gleam language

### ISSUE THREAD

**Issue by hqnna** [leonardssh/vscord#235]
Requesting support to be added for [Gleam](https://gleam.run/). The logo can be found [here](https://github.com/gleam-lang/branding/tree/main/lucy).

**Comment by hqnna** [comment]
bump on this

**Comment by hqnna** [comment]
any updates :(

**Comment by leonardssh** [comment]
Hi, you can do this yourself by following: [ADDING_LANGUAGE](https://github.com/leonardssh/vscord/blob/main/ADDING_LANGUAGE.md)

**Comment by hqnna** [comment]
Does that not require making a PR?

**Comment by leonardssh** [comment]
> Does that not require making a PR?

Yes it does.

**Comment by ItsPi3141** [comment]
@leonardssh @hqnna This can be closed. Gleam was added in #291. Icon was updated in #303
