### ISSUE TITLE
Command `vscord.reconnect` not found

### ISSUE THREAD

**Issue by TheGenocides** [leonardssh/vscord#238]
I cant use the ext everytime I opened VSCode except the first time I used it (after I install the ext)

![image](https://github.com/leonardssh/vscord/assets/82718066/8b1cae39-8f0a-4c6a-b3c1-44d7fb291676)

**Comment by nick22985** [comment]
- Could you show the debug logs for this error in the output console? `Output > VSCord`
- Also enable in the settings `Extensions > Discord Rich Presence > Advanced`
- if possible, include any errors / warning relating to this from the developer tools in vscode you can get this up by hitting ctr + shift + I

**Comment by OGFaisalN** [comment]
Hi! Been having the same issue constantly.

Extensions > Discord Rich Presence > Advanced
On, restarted

Output > VSCord
```
[10:29:43 PM] [INFO] [data.ts] ext(): Extension
[10:29:43 PM] [INFO] [data.ts] ext(): Changed to Extension
[10:29:43 PM] [INFO] [data.ts] [data.ts] ext(): activate
```

Only error I could find from Developer Tools is below. Thanks!

![image](https://github.com/leonardssh/vscord/assets/84286255/f403418d-3ce5-4722-8533-6ea1224ff719)

**Comment by EDM115** [comment]
just got the exact same error

**Comment by nick22985** [comment]
@xhayper this can be closed also missed it 

#320 fixes this
