### ISSUE TITLE
File name not showing correctly

### ISSUE THREAD

**Issue by T0kyoB0y** [leonardssh/vscord#239]
Arch - Hyprland

The file name is not displayed correctly. Instead of the file name, "file" is displayed, however all other data is displayed correctly:

![image](https://github.com/leonardssh/vscord/assets/119447307/b5cbf2c3-e188-4a8b-bea3-f68ffb36f7d2)

**Comment by jchuder** [comment]
Turn it off and you will see. 🙂
<img width="526" alt="image" src="https://github.com/leonardssh/vscord/assets/61487174/b4db51ee-69f3-44ba-ac82-c12e0625de9e">
