### ISSUE TITLE
Ignore organization does not work

### ISSUE THREAD

**Issue by jasperfirecai2** [leonardssh/vscord#246]
The setting to ignore repositories from a certain git organization does not work after the migration from old settings to new, which meant that it was showing my private work without me even knowing. I've tried using a plain string, a slug and a regex but no matter what it will not ignore based on organization.

**Comment by nick22985** [comment]
Hey,
This seems to be working for me / I cannot recreate this. What field is being leaked? I tested with all the below fields, and they all seem to be working? What behaviour do you expect this to do? 

{git_owner}
{git_provider}
{git_repo}
{git_branch}
{git_url}

**Comment by jasperfirecai2** [comment]
Gosh i just rubber ducky debugged myself in a git issue. I could've sworn it was showing the org name and a view repo button now matter what i changed in the ignore org settings, but now all of those fields are reduced to whitespace and only in matching orgs...
