### ISSUE TITLE
Git branch string

### ISSUE THREAD

**Issue by exiva** [LeonardSSH/vscord#25]
Could a string token be added for showing the current git branch?

**Comment by LeonardSSH** [comment]
The extension doesn't have git support yet, just the button that takes you to the repo. 

In the future, maybe I'll add this feature.😅

**Comment by Tim-Tech-Dev** [comment]
@LeonardSSH I have started implementing git branches into this extension.  

@exiva Should I also add a repository string, and if so should it be extracted from the folder name or the remote URI?

Example: If I would to clone the `myProject-docs` repo into the `docs` folder of `myProject` (also a git repo).  
Should the git repository string be `myProject`, `myProject-docs` or `docs`
