### ISSUE TITLE
Rich Presence always shows Idling when connected over Remote SSH

### ISSUE THREAD

**Issue by Davoleo** [leonardssh/vscord#26]
![image](https://user-images.githubusercontent.com/24458276/132982061-04447c76-7eca-4491-8916-7367a3fea2fa.png)
Despite having opened and edited multiple files.

Extension used:
![image](https://user-images.githubusercontent.com/24458276/132982087-6aca0459-8b5b-417d-b95f-799144f2f139.png)

After some time it also got like this :thonk: 
![image](https://user-images.githubusercontent.com/24458276/132983135-e41b243d-7fe2-4936-be98-94e60f0ace12.png)

**Comment by LeonardSSH** [comment]
I need to do some debugging 🙄

**Comment by hallainea** [comment]
same here :D

**Comment by LudovicoSforza** [comment]
Maybe because of this?
![image](https://user-images.githubusercontent.com/44255157/147492444-b4de02d7-cb1a-4a0c-a168-8407f6c36ab9.png)

**Comment by LeonardSSH** [comment]
@LudovicoSforza is possible, since the extension runs on the local host, I don't think it can be fixed to run in another environment. I will try to solve this problem too, if I can find a way to do it.

**Comment by xhayper** [comment]
Should be fixed... i hope....

**Comment by execrate0** [comment]
We can make a pr to fix it ?
