### ISSUE TITLE
😭 Icon gruntfile is not appear

### ISSUE THREAD

**Issue by PunGrumpy** [leonardssh/vscord#260]
### `⚠️` Issue on icon

![Preview issue](https://github.com/leonardssh/vscord/assets/108584943/8afaf426-70cd-4a73-979a-cb3381af44bb)

When I open `gruntfile.js` and checking on Discord RPC icon it's not appear

**Comment by nick22985** [comment]
Weird it looks like there never has been an image for gruntfile looked through commit history and cant find it. Someone will have to make one or I could be blind
