### ISSUE TITLE
RPC not starting & showing in discord

### ISSUE THREAD

**Issue by Flustix** [leonardssh/vscord#27]
Every time i try starting the rpc by pressing F1 and typing "Discord Rich Presence: Enable Discord Presence in the current workspace" it gives me this error, and nothing is showing up in my discord activity

![image](https://user-images.githubusercontent.com/65369281/133929703-db7131c0-2985-4b92-b6cf-7ebc82d6384d.png)

**Comment by LeonardSSH** [comment]
https://github.com/LeonardSSH/vscord/issues/38#issuecomment-974157634

**Comment by TechStudent11** [comment]
Same here. None of the commands work.

**Comment by TechStudent11** [comment]
> [#38 (comment)](https://github.com/LeonardSSH/vscord/issues/38#issuecomment-974157634)

@LeonardSSH None work for me. I installed Discord from https://discord.com, I've restarted both programs and nothing works.

**Comment by LeonardSSH** [comment]
Hey @TechStudent1, I know the problem, I spotted it some time ago, still haven't tried to find a solution, but I'll look into it. 

Question, does the extension not work at all? Or just its commands?

**Comment by TechStudent11** [comment]
> Hey @TechStudent1, I know the problem, I spotted it some time ago, still haven't tried to find a solution, but I'll look into it.
> 
> Question, does the extension not work at all? Or just its commands?

None of the commands work and just throw errors.

**Comment by LeonardSSH** [comment]
Have you tried a fresh install of the extension?

Can you show me what your logs show? 
![image](https://user-images.githubusercontent.com/35312043/151635027-d6a4927f-86fd-46c4-8e99-a9b6f1b7e68c.png)

**Comment by TechStudent11** [comment]
wait It's...

working

![image](https://user-images.githubusercontent.com/76978184/151635169-d11c19b8-2989-4995-8fd0-ec5e7583c693.png)

**Comment by LeonardSSH** [comment]
That's good, it means it connects to the discord-ipc.

1. Do you have other extensions like this that may disrupt the functionality of my extension?
2. Have you tried other extensions like this, do those work?

**Comment by LucasVinicius314** [comment]
I'm having the same problem for some time now, it's really weird, sometimes it just won't show on discord. Trying to start it manually doesn't work either, and sometimes just restarting vscode works.

Checking the rpc logs, this is all I have:
![image](https://user-images.githubusercontent.com/58010418/151663948-e888511c-6812-4b3c-b524-75091fb0acb9.png)
![image](https://user-images.githubusercontent.com/58010418/151663963-140a5369-e206-4c3c-bb7a-39ee6b741f3c.png)
![image](https://user-images.githubusercontent.com/58010418/151664036-660fac9b-d132-43cb-bde1-055a4be3ee8b.png)

Note: I have 2 instances running right now but this has never been a problem in the past, and it also breaks with only one instance running too. It's just very weird.

When it breaks, it seems to attempt a connection, and upon trying to connect manually this happens:
![image](https://user-images.githubusercontent.com/58010418/151664140-49a72655-af55-4059-9ce0-bc193b4a2d28.png)

It also says ``rpc.disable`` doesn't exist.

I haven't reinstalled it yet to see if it goes back to working as it used to, but I'm just noting this here in case it persists even after a fresh install.

**Comment by TechStudent11** [comment]
> 1\. Do you have other extensions like this that may disrupt the functionality of my extension?

I don't think so.

> 2\. Have you tried other extensions like this, do those work?

Yes I have. [icrawl.discord-vscode](https://marketplace.visualstudio.com/items?itemName=icrawl.discord-vscode) automatically connected to my Discord Client.

**Comment by LeonardSSH** [comment]
I'll see what I can do.

**Comment by TechStudent11** [comment]
> I'll see what I can do.

Alright. The commands still don't work after a reinstallation, so that's probably a problem with the extension.

**Comment by LeonardSSH** [comment]
Please upgrade the extension and try again.

**Comment by TechStudent11** [comment]
Alright

**Comment by LeonardSSH** [comment]
@TechStudent11 any news, does it work?

**Comment by TechStudent11** [comment]
I wasn't able to upgrade it yesterday.

So I have updated it and... What'll you know?

![image](https://user-images.githubusercontent.com/76978184/152563515-734152db-1ae7-45e5-8f7a-a27a507deb98.png)

**Comment by LeonardSSH** [comment]
Ok, that's really weird...  I don't know what it could be from, I've tested all the media, it works perfectly for me. 

Can you provide me more details? 

- Where do you get the extension from?
- What version of vscode do you have?
- What windows do you have? What build?

**Comment by TechStudent11** [comment]
> * Where do you get the extension from?

The VSCode marketplace.

> * What version of vscode do you have?

VSCode 1.64.0

```bash
P:\>code -v
1.64.0
5554b12acf27056905806867f251c859323ff7e9
x64
```

> * What windows version/build do you have?

Windows 11 21H2 OS Build 22000.318

And, my Discord version is 

![image](https://user-images.githubusercontent.com/76978184/152567274-0b88c2ad-135c-4ef6-9de2-50390127ad76.png)

It says Windows 10, but I am on Windows 11.

**Comment by LeonardSSH** [comment]
Ok, I've the same environment. Honestly, I don't think I can help you, I can't really figure out at the moment, what could be causing your problem, you should try debugging the extension, modifying the source code installed on your PC. It's a sure way to troubleshoot the problem and possibly report it here to fix it.

**Comment by TechStudent11** [comment]
> Ok, I've the same environment. Honestly, I don't think I can help you, I can't really figure out at the moment, what could be causing your problem, you should try debugging the extension, modifying the source code installed on your PC. It's a sure way to troubleshoot the problem and possibly report it here to fix it.

okay. I'll try some time, but probably not today

**Comment by BenitzCoding** [comment]
<img width="1552" alt="Screenshot 2022-04-01 at 15 51 46" src="https://user-images.githubusercontent.com/70798458/161220250-ace62e89-cee9-4db7-9ac8-16b399c6b3c5.png">

**Comment by Reven208** [comment]
It happens to me too, although I try to "reconnect" from the command palette

ERROR: (spanish)
https://femboy.wtf/Reven/🐦🍳👢🥟

exit: (spanish)
https://femboy.wtf/Reven/🚧🍙🥘🛀

But if I close my workspace ,it works.
https://femboy.wtf/Reven/💺🌁🎭🧀

**Comment by yoni13** [comment]
```
[下午7:34:56 - INFO] [data.ts] ext(): Git extension is active
[下午7:34:57 - INFO] Discord Rich Presence for VS Code activated.
[下午7:34:57 - INFO] Registered Discord Rich Presence commands
[下午7:34:57 - ERROR] Encountered following error while trying to login:
Error: Could not connect
[下午7:34:57 - INFO] [002] Destroyed Discord RPC client
[下午7:35:08 - INFO] Reconnecting to Discord Gateway...
[下午7:35:08 - INFO] [003] Destroyed Discord RPC client
[下午7:35:08 - ERROR] Encountered following error while trying to login:
Error: Could not connect
[下午7:35:08 - INFO] [002] Destroyed Discord RPC client
[下午7:35:26 - INFO] Reconnecting to Discord Gateway...
[下午7:35:26 - INFO] [003] Destroyed Discord RPC client
[下午7:35:26 - ERROR] Encountered following error while trying to login:
Error: Could not connect
[下午7:35:26 - INFO] [002] Destroyed Discord RPC client
[下午7:35:55 - INFO] Reconnecting to Discord Gateway...
[下午7:35:55 - INFO] [003] Destroyed Discord RPC client
[下午7:35:55 - ERROR] Encountered following error while trying to login:
Error: Could not connect
[下午7:35:55 - INFO] [002] Destroyed Discord RPC client
```
logs
