### ISSUE TITLE
Please publish your extension to the Open VSX registry

### ISSUE THREAD

**Issue by jbmagination** [LeonardSSH/vscord#29]
Publishing your extension to this registry would open up the extension to many more users.

a) Many Linux builds use the Open VSX registry (https://wiki.archlinux.org/title/Visual_Studio_Code#No_extensions_found)
> The packages are configured to use the Open VSX registry instead of the Microsoft one. This explains why some extensions are missing from the vscode explorer while they appear to be listed online. 

b) VSCodium support
> According to the VS Code Marketplace Terms of Use, you may only install and use Marketplace Offerings with Visual Studio Products and Services. For this reason, VSCodium uses open-vsx.org, an open source registry for VS Code extensions.

Please consider this 🙏

**Comment by LeonardSSH** [comment]
https://open-vsx.org/extension/vscord-extension/vscord

Can you try if the extension works well? 😊 Thx.

**Comment by jbmagination** [comment]
Everything's working :+1:
