### ISSUE TITLE
No RPC

### ISSUE THREAD

**Issue by AmtixDev** [leonardssh/vscord#295]
The extension is very good and I recommend it but sometimes don't show **RPC**, Even when I enabled Activity Privacy, I hope you fix it.

Proof:
![image](https://github.com/leonardssh/vscord/assets/107303548/7abffefe-8eb5-456a-9c66-3e2e75e22869)

![image](https://github.com/leonardssh/vscord/assets/107303548/271c8a39-b2ed-4aa7-a7ce-52ce646ba490)

**Comment by raishudesu** [comment]
i think this solution worked for me. this setting under Privacy & Safety should be enabled

![image_2024-03-19_141724475](https://github.com/leonardssh/vscord/assets/105921989/a7f9536f-ebe9-4e92-9a27-04d91392479c)

**Comment by Tevtongermany** [comment]
it could be because you are switching folders
