### ISSUE TITLE
Failed to reconnect to Discord Gateway Couldn't connect to Discord via RPC: RPC_COULD_NOT_CONNECT

### ISSUE THREAD

**Issue by SlyTheFloof** [leonardssh/vscord#312]
Couldn't connect to Discord via RPC: RPC_COULD_NOT_CONNECT

**Comment by lkxoayh** [comment]
Yeah i have this too
[00:36:49] [ERROR] Encountered following error while trying to login: RPC_COULD_NOT_CONNECT: Could not connect
    at c:\Users\user\.vscode\extensions\leonardssh.vscord-5.2.9\node_modules\.pnpm\@xhayper+discord-rpc@1.1.2\node_modules\@xhayper\discord-rpc\dist\transport\IPC.js:111:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[00:36:49] [INFO] [002] Destroyed Discord RPC client
[00:37:44] [INFO] Reconnecting to Discord Gateway...

**Comment by drylian** [comment]
i too

**Comment by amolinarius** [comment]
I've the same problem but I don't think it's coming from this extension
I've this error since I updated Discord and `icrawl.discord-vscode` isn't working either

**Comment by amolinarius** [comment]
I uninstalled Discord and reinstalled it yesterday, it's working again for me. I created a bug report on Discord

**Comment by Deep0Thinking** [comment]
I encountered the same issue.
