### ISSUE TITLE
Extension never loads

### ISSUE THREAD

**Issue by polygonnedpotato** [leonardssh/vscord#318]
```
2024-05-07 15:03:31.556 [info] ExtensionService#_doActivateExtension LeonardSSH.vscord, startup: false, activationEvent: 'onStartupFinished'
2024-05-07 15:03:31.741 [error] Activating extension LeonardSSH.vscord failed due to an error:
2024-05-07 15:03:31.741 [error] Error: Extension 'vscode.git' is not known or not activated
```

Using latest VSCode Insider build on windows.

**Comment by nick22985** [comment]
This error confuses me and always has, even without `vscode.git` installed, which theoretically should be impossible as it is build into vscode. It should gracefully disable git features. I can not replicate this even by setting `"git.enabled":` false, in my config

Could you try enabling debug in Discord Rich Presence > Advanced > Behaviour: Debug and showing the logs from that

https://github.com/leonardssh/vscord/blob/db93eaa24900520f6ab5294e542a7693ad45fd76/src/data.ts#L208-L231

**Comment by EDM115** [comment]
well, the fact that `vscode.git` takes ages to load is known (see https://github.com/microsoft/vscode/issues/183199 as example)  
so VSCord may just fail to load because git isn't loaded yet. maybe the extension could wait for vscode's git to launch before starting ?

**Comment by Mopsgamer** [comment]
The git extension sometimes loads later than vscord requires it. There must be a way to wait for the git extension to load.
