### ISSUE TITLE
Show "Not in a file" when opening jupyter notebook

### ISSUE THREAD

**Issue by SurgeBay** [leonardssh/vscord#327]
![Screenshot 2024-07-03 030319](https://github.com/leonardssh/vscord/assets/101690709/9a80a816-d6b2-4b7e-b01a-4be1a4744b4f)

**Comment by nick22985** [comment]
ipynb has its own api's that need to be supported see #120

**Comment by NiceCats** [comment]
Unfortunately, it is still a work in progress. I have tried other extensions and they work fine; however, this particular one is not functioning well.

**Comment by xhayper** [comment]
Duplicated of #120
