### ISSUE TITLE
View repository not showing up.

### ISSUE THREAD

**Issue by Jaxiii** [leonardssh/vscord#328]
Public repo not showing up.
tried to add in settings.json, but still nothing.

**Comment by nick22985** [comment]
What is your current config?

**Comment by Jaxiii** [comment]
> What is your current config?

MacBook Pro 2021
M1 Pro
16GB
MacOS Soma 14.3

Discord Version: 0.0.309

this is the current one, but default and other variations of this configuration lead to the same result, the button won't show.

name, description, branch and other configs, display and change fine.

```
{
    "vscord.app.name": "Visual Studio Code",
    "vscord.ignore.organizations": [
        "https://github.com/espresso-cash"
    ],
    "vscord.status.buttons.button1.git.active.enabled": true,
    "vscord.status.buttons.button1.git.active.url": "https://github.com/espresso-cash/espresso-cash-public",
    "vscord.ignore.repositories": [
        "https://github.com/espresso-cash/espresso-cash-public"
    ]
}
```

**Comment by junaga** [comment]
I have the same issue. and the `{git_url}` variable seems to be not working

**Comment by DatCodeMania** [comment]
Same issue here.

**Comment by EDM115** [comment]
same here, but I thought it was due to the discord UI redesign, as the activities are simplified I just thought they got rid of the buttons

**Comment by nick22985** [comment]
Buttons dont show on your own account anymore due to a discord change. If you log in on another browser they should show up.

![image](https://github.com/user-attachments/assets/bb770819-a391-4e76-95ed-c3d7d2fd5dfc)

**Comment by nick22985** [comment]
There is no solution. Discord RPC support has been deprecated for years now. The problem is with Discord, so there is nothing we can do. People will see the buttons, but you won't be able to.

**Comment by Jaxiii** [comment]
> There is no solution. Discord RPC support has been deprecated for years now. The problem is with Discord, so there is nothing we can do. People will see the buttons, but you won't be able to.

F boyz

**Comment by EDM115** [comment]
hahaa  
guys his internship will end soon if it's not already ended :(
