### ISSUE TITLE
Changing "Code"

### ISSUE THREAD

**Issue by SummerToast** [leonardssh/vscord#329]
halloo, how would i change the "Code" or Playing "Code" and is there way to change picture in the rpc

**Comment by SummerToast** [comment]
![image](https://github.com/user-attachments/assets/37ed7e62-e7da-44f4-8db2-ba9563971af3)

**Comment by stevenj2019** [comment]
having same confusion, it explains the variable to change, but not where or how to change it

**Comment by ItsPi3141** [comment]
You can change the `vscord.app.name` option
