### ISSUE TITLE
WSL - Remote Support

### ISSUE THREAD

**Issue by ghost** [leonardssh/vscord#36]
I'm using `WSL - Remote` extension for coding in Windows environment but vscord doesn't support it, so presence doesn't work properly when I open the file. It shows the status as idle.
![image](https://user-images.githubusercontent.com/83988414/141642639-73bdfbc9-2b02-42a6-934a-1aa093ab69b9.png)
![image](https://user-images.githubusercontent.com/83988414/141642590-e8512ae4-38f1-47fd-b320-4ccd3e575702.png)

**Comment by mrstoffer** [comment]
I encounter the same problem when doing a Live Share session

**Comment by st4tic-rr** [comment]
Remote - SSH doesn't work either, I believe. Same Idle issue.
![image](https://user-images.githubusercontent.com/22870471/142076930-9a62ed86-9350-4957-9f99-b28c5275ef34.png)
(edited lang config values)

**Comment by egorlight04** [comment]
I'm using WSL too, but I haven't met any problems with it. Presence works fine.
But the one thing, that I noticed is lack of GitHub Repository button. It doesn't work with WSL...

**Comment by LeonardSSH** [comment]
@egorlight04 have you activated it? `rpc.buttonEnabled` it is disabled by default.

**Comment by egorlight04** [comment]
Yes, I have. I also checked this feature without WSL and it works perfectly.

**Comment by srjheam** [comment]
> I'm using WSL too, but I haven't met any problems with it. Presence works fine. But the one thing, that I noticed is lack of GitHub Repository button. It doesn't work with WSL... ![image](https://user-images.githubusercontent.com/61929662/154805962-c91e9849-a93d-40e7-a8da-29cf0773c2f8.png)

Same here. "View Repository" button doesn't show when I am in any workspace remote connected through WSL.
![image](https://user-images.githubusercontent.com/58143641/175787032-33fd9e2e-4ea5-4f08-aa31-0789ef47b354.png)
![image](https://user-images.githubusercontent.com/58143641/175787061-4adbff1f-0888-427e-b753-2a340be7e376.png)

**Comment by xhayper** [comment]
Should be fix in dd7e1b6397cd147020df6dcd9b033e5e02ae5c89

Reopen the issue if it doesn't

**Comment by DrumSlayers** [comment]
> Same here. "View Repository" button doesn't show when I am in any workspace remote connected through WSL.

I still have the exact same issue.
What have you done for it to work ?

I don't remember the git repo button showing up a single time when using vscode through WSL to be honest.

**Comment by Patai5** [comment]
Doesn't work for me either.

From the logs, it seems like the `vscode.git` extension is not properly loaded:
```log
[INFO] [data.ts] ext(): undefined
```
Loading of the extension in source and the log:
https://github.com/leonardssh/vscord/blob/f7579e62f3972b76da62a73bae5e7e867266096f/src/data.ts#L211-L212

---
I've tried quickly debugging it, but with my lack of experience of developing vscode extensions that went about as expected 🙃 

Interestingly though, when I ran vscord in the debugger, the extension loaded properly from the path:
`/home/lukyn/.vscode-server/bin/258e40fedc6cb8edf399a463ce3a9d32e7e1f6f3/extensions/git`

But then discord failed to connect every time, so that's that for my debugging...
```log
COULD_NOT_CONNECT: Could not connect
    at /home/lukyn/programming/vscord/node_modules/.pnpm/@xhayper+discord-rpc@1.2.2/node_modules/@xhayper/discord-rpc/dist/transport/IPC.js:121:20
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
