### ISSUE TITLE
Elapsed time resets after exceeding 24 hours

### ISSUE THREAD

**Issue by redssu** [LeonardSSH/vscord#39]
Hey,

I noticed that when the "elapsed time" exceeds the value of 24 hours, the elapsed time "resets".

What do I mean exactly?

If I was programming for 25 hours, it shows on the discord that I was programming only for 1 hour.
The expected result would be for example "elapsed: 1 day" or ideally just "elapsed: 25:00:00"

I have looked at the code of this extension but I didn't see anything that could cause this bug.

Cheers!

**Comment by LeonardSSH** [comment]
you're crazy. 🤣😂

**Comment by williamd5** [comment]
This is an issue with Discord. On the desktop app, when the time exceeds 24 hours, it will start again from 0. On other clients, such as Discord for Android, the time does not reset (and as far as I remember) adds a new number for days.

**Comment by LeonardSSH** [comment]
@williamd5 interesting, then given that, there's not much I can do about this issue.

**Comment by williamd5** [comment]
Just some more context for anyone that finds this issue:

Desktop (Linux Ubuntu 20.04, Discord stable)
![image](https://user-images.githubusercontent.com/66572326/146771959-74be7016-143f-43df-9b15-725fde6ff744.png)

Mobile (Linux Android 10, Discord stable)
![image](https://user-images.githubusercontent.com/66572326/146772246-b781edf1-6f38-41cc-be3c-ea6c9005a46d.png)

**Comment by xhayper** [comment]
This was caused by discord not supporting more than 24 hours in timestamp.
