### ISSUE TITLE
LICENSE Issues

### ISSUE THREAD

**Issue by iCrawl** [LeonardSSH/vscord#4]
You took a lot of code from:
- https://github.com/iCrawl/discord-vscode
- https://github.com/Satoqz/vscode-discord

but mention neither in your LICENSE file, this is violating the MIT LICENSE.

To resolve this, a copyright notice like here:
https://github.com/LeonardSSH/vscord/blob/3afb78cfb22d2f3311882fca3c8a6a451fe86963/LICENSE#L3

for both Satoqz and me (iCrawl) with the proper year of when the last code pieces were taken is sufficient to resolve this.

**Comment by LeonardSSH** [comment]
Solved. Sorry for the inconvenience. 😊
