### ISSUE TITLE
Add support for Terraform

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [LeonardSSH/vscord#41]
Hey,

Is it possible to add support for [Terraform](https://www.terraform.io/), file extensions `.tf` and `.tfvars`? I can't open a PR if you want!

Thanks,
MiguelNdeCarvalho

**Comment by LeonardSSH** [comment]
It will be in the next update with everything added along the way.

**Comment by LeonardSSH** [comment]
![image](https://user-images.githubusercontent.com/35312043/147769625-cb45d841-2761-41bf-8c2d-66d9338ecec6.png)

**Comment by MiguelNdeCarvalho** [comment]
Thanks @LeonardSSH

**Comment by LeonardSSH** [comment]
A new version will be released soon, after I fix some issues.
