### ISSUE TITLE
Git Ignore Repo / Git Ignore Org / Replace workplace 

### ISSUE THREAD

**Issue by nick22985** [LeonardSSH/vscord#42]
- [x] Add the ability to have a exluded repos from displaying. Have it so if the repo matches the ignored list then have it not display on the button
- [x] Add the ability to exlude git repo orginastions from displaying a link to the git repo
- [x] Add the ability instead of completly not starting the extension when a ignored list is started make it so that you can put some other text in replace of the data that you do not want to say. Example if it is the project u could change it to say [Redacted] or something like that so people can still see that you are coding just cant see what u are coding.

**Comment by LeonardSSH** [comment]
For those related to git, @Tim-Tech-Dev needs to finish implementing https://github.com/LeonardSSH/vscord/pull/35. 

The last one can be done.

**Comment by LeonardSSH** [comment]
> Add the ability instead of completly not starting the extension when a ignored list is started make it so that you can put some other text in replace of the data that you do not want to say. Example if it is the project u could change it to say [Redacted] or something like that so people can still see that you are coding just cant see what u are coding.

Here's @nick22985 - https://github.com/LeonardSSH/vscord/commit/d8db14b24c00452edf5b10a4b5821210dabca5c1
I am now working on implementing the other suggestions.

**Comment by LeonardSSH** [comment]
> Add the ability to have a exluded repos from displaying. Have it so if the repo matches the ignored list then have it not display on the button

https://github.com/LeonardSSH/vscord/commit/82c7b3b8d0d7f7e786c73f0194495261fb362820

**Comment by LeonardSSH** [comment]
https://github.com/LeonardSSH/vscord/commit/ccf27842ba7b1d4fca1e29f8bb64925b1ae9c68e
