### ISSUE TITLE
Running in debug Cannot use import statement outside a module.

### ISSUE THREAD

**Issue by nick22985** [LeonardSSH/vscord#43]
I am getting this error when trying to run the plugin in debug mode in vscode. I am compiling and using `npm run watch` am i doing something dumb?
```
Activating extension 'vscord-extension.vscord' failed: Cannot use import statement outside a module.
```

**Comment by LeonardSSH** [comment]
To be able to debug the extension, you must compile the extension using `npm run build`, 'cause the extension must use webpack build, not tsc (watch) one.

**Comment by nick22985** [comment]
Ahh i see ty.
