### ISSUE TITLE
Github Repo TypeError: Cannot read property 'repository' of undefined

### ISSUE THREAD

**Issue by nick22985** [LeonardSSH/vscord#45]
When switching to another git repo in the same workspace it will cause this error. 
```
stack trace: TypeError: Cannot read property 'name' of undefined
    at details (/HDD/1TBSSD/projects/Personal/vscord/src/activity.ts:142:50)
    at activity (/HDD/1TBSSD/projects/Personal/vscord/src/activity.ts:39:1)
    at sendActivity (/HDD/1TBSSD/projects/Personal/vscord/src/extension.ts:17:27)
    at /HDD/1TBSSD/projects/Personal/vscord/src/listener.ts:16:244
    at u.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at Data.updateGit (/HDD/1TBSSD/projects/Personal/vscord/src/data.ts:189:1)
    at /HDD/1TBSSD/projects/Personal/vscord/src/data.ts:169:1
    at /opt/visual-studio-code/resources/app/extensions/git/dist/main.js:2:1045061
    at u.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at m.open (/opt/visual-studio-code/resources/app/extensions/git/dist/main.js:2:991145)
    at m.openRepository (/opt/visual-studio-code/resources/app/extensions/git/dist/main.js:2:989724)
    at i (/opt/visual-studio-code/resources/app/extensions/git/dist/main.js:2:943438)
    at /opt/visual-studio-code/resources/app/extensions/git/dist/main.js:2:989054
    at async Promise.all (index 0)
    at m.onDidChangeVisibleTextEditors (/opt/visual-studio-code/resources/app/extensions/git/dist/main.js:2:988953)
```

Possibly something to do with a variable not being set when it detects a git repo switch

**Comment by LeonardSSH** [comment]
A reproduction code? 'Cause I can't reproduce it.

**Comment by nick22985** [comment]
It not doing it now.
Closing as it seems it is not doing it now

**Comment by nick22985** [comment]
Reopening this I have reacted it with the deployed version.
https://youtu.be/8K8ehSd_ig0

**Comment by LeonardSSH** [comment]
The only thing I haven't tested, in non-git environment. 😄

**Comment by nick22985** [comment]
lmao always the way xD

**Comment by nick22985** [comment]
Another thing to note. Now if you open vscode inside with a file already open. The rpc will not display. Until changing the file. This issue might be related to something about when a git repo isnt detected it does show anything maybe?

**Comment by LeonardSSH** [comment]
I've found the problem, yep, it's related to the Git API. I've almost got it.

**Comment by nick22985** [comment]
Updates now but does nto clear out the repo url button. So when switching from a git repo to the non git repo it will display the button to link back to your previous repo. If you have Rpc: Button Incative label / Button inactive url set. It also does not update the values to those correct values as well

**Comment by LeonardSSH** [comment]
I'm investigating... :shipit:

**Comment by LeonardSSH** [comment]
@nick22985 can you test it now?

**Comment by nick22985** [comment]
When folder is not in a repo. Does not display Inactive button. Switching now is working

**Comment by nick22985** [comment]
Think i found the probelem

**Comment by nick22985** [comment]
So this is the fix
Line  130 in activity.ts. The problem is that dataClass.gitRemoteUrl} needs to be changed to a asynchronous function so that it waits to see the results from the api call before returning. This way we dont run into issues with if the API has not returned the a value it going to the inactive git repo button and u having to wait until u switch files again for it to update
```js
		if (config[CONFIG_KEYS.ButtonEnabled]) {
			console.log(`${dataClass.gitRemoteUrl}`);
			if (dataClass.gitRemoteUrl) {
				const gitRepo = dataClass.gitRemoteUrl.toString('https').replace(/\.git$/, '');
				const gitOrg = dataClass.gitRemoteUrl.organization ?? dataClass.gitRemoteUrl.owner;

				const isRepositoryExcluded = isExcluded(config[CONFIG_KEYS.IgnoreRepositories], gitRepo);
				const isOrganizationExcluded = isExcluded(config[CONFIG_KEYS.IgnoreOrganizations], gitOrg);

	 			const isNotExcluded = !isRepositoryExcluded && !isWorkspaceExcluded && !isOrganizationExcluded;

				if (gitRepo && config[CONFIG_KEYS.ButtonActiveLabel] && isNotExcluded) {
					presence = {
						...presence,
						buttons: [
							{
								label: config[CONFIG_KEYS.ButtonActiveLabel],
								url: gitRepo
							}
						]
					};
				}
			} else if (!dataClass.gitRemoteUrl && config[CONFIG_KEYS.ButtonInactiveLabel] && config[CONFIG_KEYS.ButtonInactiveUrl]) {
```

**Comment by LeonardSSH** [comment]
Yeah, I think I need to take a look at the Data class code, get it purified.

**Comment by nick22985** [comment]
The other thing when i was looking around trying to fix it. It also looks like it resets the presence every time so for a second u see the idle state then it switches to the config.

**Comment by LeonardSSH** [comment]
Yeah, that's what I noticed, something is wrong.

**Comment by danivideda** [comment]
I was about to raise an issue where the 'View Repository' button didn't do anything.
Is this what caused it?

**Comment by LeonardSSH** [comment]
@danivideda discord related stuff. See https://github.com/LeonardSSH/vscord/issues/20#issuecomment-901091316

**Comment by LeonardSSH** [comment]
@nick22985 the problem still persist? After the last couple updates?
@danivideda the problem seems to be solved, I think the people at discord have finally made it so you can click your own button (at least it works for me)

**Comment by nick22985** [comment]
Sorry for the late response @LeonardSSH.
Yea the issue seems to have been Fixed.
