### ISSUE TITLE
Request: Could you make version 3.2.3 avaliable to install from the marketplace again?

### ISSUE THREAD

**Issue by MRSS02** [leonardssh/vscord#47]
I dislike the changes made in version 4.0.0, as for me at least it has the bugs of the bottom idle message not showing, and it updates the rich presence far more slowly. I had to format my system and was going to install that version again; but apparently it is gone from the marketplace? I could try building it from source but i have no idea how to tbh, i tried running the build but it always gives me errors  

Edit: apparently it seems the bottom message not showing issue is solved / being solved - however i still dislike the newer version's slower responsiveness when updating user status

**Comment by LeonardSSH** [comment]
In answer to the topic of this issue, you can choose which version you want from the extensions tab in vscode. 

![image](https://user-images.githubusercontent.com/35312043/149141090-686e83da-c63e-468f-ad4e-315d951b78ef.png)

**The bottom idle message** is not a issue, that feature has been put under a setting, and whoever wants to can activate it. 
Release [v4.3.0](https://github.com/LeonardSSH/vscord/releases/tag/v4.3.0)

Commit https://github.com/LeonardSSH/vscord/commit/a6e2c354bfb6c56440fe1f959207a5edd422d2ae

```jsonc
{
  // set to false if you want to appear in presence
  "rpc.removeLowerDetailsIdling": false
}
```

---

> however i still dislike the newer version's slower responsiveness when updating user status

Can you give me more details?
