### ISSUE TITLE
`.astro` extension is not supported

### ISSUE THREAD

**Issue by tuhanayim** [LeonardSSH/vscord#48]
`.astro` extension is not supported, so big image pretends as I'm editing txt file.
https://astro.build
![image](https://user-images.githubusercontent.com/83988414/151553526-28e3a40b-0eef-4710-9bda-67aceb0673d4.png)

**Comment by LeonardSSH** [comment]
Could you provide me more info about Astro? Like file extensions related to, some icons.

**Comment by tuhanayim** [comment]
Astro is a static site builder. It ships less JavaScript and you can use it on almost all framework/libraries. You can even mix and use them like Vue and SolidJS, Svelte and Lit or Svelte, Vue, React and Alpine. Also Astro has awesome built-in features and components.
File extension is `.astro`.
### Normal Logo
![image](https://user-images.githubusercontent.com/83988414/151581766-97f76140-e29e-4dc2-9e40-1f4801f3f1c3.png)
### vscode-icons' logo
![image](https://user-images.githubusercontent.com/83988414/151581253-dc034e69-8e40-48db-a485-9126819b8d15.png)

**Comment by LeonardSSH** [comment]
Good, I will do support, it will be available in the next patch version. Thx.
