### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ethamitc** [LeonardSSH/vscord#5]
Their appears to be a minor memory leak.
![image](https://user-images.githubusercontent.com/27776796/109516465-3a6ec680-7a76-11eb-8168-1995a685bf06.png)

After disabling & reloading:
![image](https://user-images.githubusercontent.com/27776796/109516492-40fd3e00-7a76-11eb-8055-bd6ac0c10716.png)

**Comment by LeonardSSH** [comment]
Are you sure about this? I've never had this problem before. 🤔🤔

**Comment by ethamitc** [comment]
> Are you sure about this? I've never had this problem before. 🤔🤔

Positive. It resolved itself after uninstalling the extension & reloading vscode. Hours later still no issue.

**Comment by LeonardSSH** [comment]
Hmm, ok, very weird, I'll take a look to see what I did wrong. 👍

**Comment by ethamitc** [comment]
cheers.

**Comment by LeonardSSH** [comment]
The problem should be fixed in the newly released version, please upgrade to the extension and let me know if the problem is fixed.

**Comment by LeonardSSH** [comment]
https://github.com/LeonardSSH/vscord/issues/7#issuecomment-896199539
