### ISSUE TITLE
Reconnect/Disconnect discord presence from command palette throws exception

### ISSUE THREAD

**Issue by Gargantuan5k** [LeonardSSH/vscord#50]
![Command Palette](https://user-images.githubusercontent.com/73837135/151692768-32550a77-272b-4d5f-af69-8f44ba2a3f0f.png)

![Error Received](https://user-images.githubusercontent.com/73837135/151692757-cb92412f-1959-4afc-a7a4-a6c88a53fdf1.png)

I receive an error saying:

`Command 'Discord Rich Presence: Reconnect Discord Presence to Gateway' resulted in an error (Cannot read property 'write' of null)`

Every time i try to reconnect presence from the command palette. The same error happens when disconnecting presence. Tried reinstalling the extension, still getting the errors

**Comment by LeonardSSH** [comment]
Known Issue: https://github.com/LeonardSSH/vscord/issues/27

I'm going to close this because it's duplicate.

**Comment by LeonardSSH** [comment]
@Gargantuan5k Please upgrade the extension and try again.

**Comment by Gargantuan5k** [comment]
@LeonardSSH Upgraded, extension seems to be working properly for now. Will reopen this issue if there are any other problems, thanks :)
