### ISSUE TITLE
Command not found.

### ISSUE THREAD

**Issue by thearkxd** [LeonardSSH/vscord#51]
When i want reconnect to Discord Gateway, i get "Command 'Discord Rich Presence: Reconnect Discord Presence to Discord Gateway' resulted in an error (command 'rpc.reconnect' not found)" error. And all commands are like that.

OS: MacOS Monterey 12.2
Vscode Version: 1.63.2

**Comment by thearkxd** [comment]
And RPC console is always like that;
![image](https://user-images.githubusercontent.com/59927799/152142002-e6f55aaf-5f00-4b89-bd56-ccb739e6d042.png)

**Comment by christoff-linde** [comment]
I also have the exact same problem @thearkxd

**Comment by LeonardSSH** [comment]
Please upgrade the extension and try again.

**Comment by thearkxd** [comment]
Not working...

**Comment by thearkxd** [comment]
I uninstalled and reinstalled it and worked. Thanks!
