### ISSUE TITLE
Connecting to Discord Gateway... doesn't work

### ISSUE THREAD

**Issue by bender09** [leonardssh/vscord#52]
I installed the Plugin but the RPC wont work

**Comment by LeonardSSH** [comment]
Please upgrade the extension and try again.

**Comment by bender09** [comment]
also dont work

**Comment by LeonardSSH** [comment]
Please provide more info.

**Comment by bender09** [comment]
https://cdn.upload.systems/uploads/rBt35DuN.png
https://cdn.upload.systems/uploads/t9SwR6gB.png

**Comment by bender09** [comment]
i think its because the discord account switch

**Comment by LeonardSSH** [comment]
It doesn't matter, the RPC connects to discord-ipc, it doesn't matter what account you are on.

Have you tried restarting discord? Also restart the extension using `rpc.reconnect`? Or a fresh reinstall of the extension?

**Comment by LeonardSSH** [comment]
Can you provide me some extension logs?

![image](https://user-images.githubusercontent.com/35312043/152565731-8b6826f5-77cd-4460-b003-47f40b4eb3b8.png)

**Comment by bender09** [comment]
https://cdn.upload.systems/uploads/pDvE1Gsw.png

**Comment by LeonardSSH** [comment]
Hmm, with the other extensions like this on the marketplace, do you have the same problem? 
e.g with iCrawl's extension, do you have the same problem?

**Comment by bender09** [comment]
https://cdn.upload.systems/uploads/nuliqy52.png

**Comment by LeonardSSH** [comment]
Same problem with his extension. 
You tried running the discord **"run as administrator"**?

**Comment by bender09** [comment]
yes tried but also not working

**Comment by LeonardSSH** [comment]
Ok, then, I don't think I can help you, I can't really figure out at the moment, what could be causing your problem, you should try debugging the extension, modifying the source code installed on your PC. It's a sure way to troubleshoot the problem and possibly report it here to fix it. 😅

**Comment by bender09** [comment]
i dont know how i can change the code so it would work...

**Comment by bender09** [comment]
i cant run the debug mode 
https://cdn.upload.systems/uploads/6MCgOknk.png

**Comment by LeonardSSH** [comment]
You need to run `yarn build` first.

**Comment by bender09** [comment]
https://cdn.upload.systems/uploads/PRzavgdr.png

dont work

**Comment by LeonardSSH** [comment]
You don't have yarn installed, try `npm i -g yarn` and then run `yarn` & `yarn build` again

**Comment by LeonardSSH** [comment]
Or, you can use `npm` directly, by running `npm run build`.

**Comment by bender09** [comment]
https://cdn.upload.systems/uploads/29JadCDQ.png

**Comment by bender09** [comment]
https://cdn.upload.systems/uploads/IP1hxD4b.png

**Comment by LeonardSSH** [comment]
Yeap, now you can run the extension from the debugging menu.

**Comment by bender09** [comment]
how i can run this

**Comment by LeonardSSH** [comment]
![image](https://user-images.githubusercontent.com/35312043/152591898-c0db02a8-93d9-4b6d-9e4f-6a55794e15ba.png)

**Comment by bender09** [comment]
I finally managed to start but now this error comes up
https://cdn.upload.systems/uploads/G25j4WZJ.png

**Comment by MiguelNdeCarvalho** [comment]
Hey,

I am having exactly the same issue.

**Logs:**
```
[2:58:34 PM - INFO] [data.ts] ext(): Git extension is active
[2:58:34 PM - INFO] Discord Rich Presence for VS Code activated.
[2:58:34 PM - INFO] Registered Discord Rich Presence commands
[2:58:44 PM - ERROR] Encountered following error while trying to login:
Error: RPC_CONNECTION_TIMEOUT
[2:58:44 PM - INFO] [002] Destroyed Discord RPC client
```

Thanks,
MiguelNdeCarvalho

**Comment by LeonardSSH** [comment]
@MiguelNdeCarvalho try a restart to discord client, also a restart to vscode, this combo may fix the problem.

**Comment by MiguelNdeCarvalho** [comment]
Hey again, 

I have made both of them and now it connects but it no longer shows the status in **Discord**

Thanks,
MiguelNdeCarvalho

**Comment by LeonardSSH** [comment]
@MiguelNdeCarvalho can you provide some logs?

**Comment by MiguelNdeCarvalho** [comment]
My logs just show this:

```
[4:14:00 PM - INFO] [data.ts] ext(): Git extension is active
[4:14:00 PM - INFO] Discord Rich Presence for VS Code activated.
[4:14:00 PM - INFO] Registered Discord Rich Presence commands
[4:14:00 PM - INFO] Successfully connected to Discord
[4:14:00 PM - INFO] Successfully logged in to Discord with client ID **redacted**
```

**Comment by LeonardSSH** [comment]
@MiguelNdeCarvalho seems to be ok, and nothing shows up in the discord client?

**Comment by haha-classic** [comment]
Hi I have a problem like the people above
Logs:
```
[19:55:19 - INFO] [data.ts] ext(): Git extension is active
[19:55:20 - INFO] Discord Rich Presence for VS Code activated.
[19:55:20 - INFO] Registered Discord Rich Presence commands
[19:55:20 - ERROR] Encountered following error while trying to login:
Error: Could not connect
[19:55:20 - INFO] [002] Destroyed Discord RPC client
```
I use linux

**Comment by haha-classic** [comment]
I tried restarting the discord and visual studio code, it doesn't help
The latest version is installed

**Comment by LeonardSSH** [comment]
`Error: could not connect` is thrown when the [discord-rpc](https://github.com/discordjs/RPC/blob/master/src/transports/ipc.js#L32) does not detect the discord client's ipc.

Possible solutions: [iCrawl/discord-vscode#troubleshooting](https://github.com/iCrawl/discord-vscode#troubleshooting)

**Comment by haha-classic** [comment]
I'm going to try now

**Comment by haha-classic** [comment]
Your solution worked, thanks a lot!

**Comment by TomG07** [comment]
Hi! 
I was running my VSCode as Administrator, and this error apeared
![image](https://github.com/leonardssh/vscord/assets/81299743/8b4830f5-570a-4c60-855a-7401bcbcf1dd)
I runned VSC as a normal user and the error persists... 
Can anyone help me please?
Thank you!

**Comment by Foxy48** [comment]
same issue like TomG07
