### ISSUE TITLE
Error with rpc

### ISSUE THREAD

**Issue by Lolly1150** [leonardssh/vscord#57]
Hi, i have problem with rpc every time i open vsc it don't start,to fix it i reinstall this excention

**Comment by Hyperclaw79** [comment]
@LeonardSSH Not sure if this is the actual fix but, restarting the Discord client after VSCode is already open seems to resolve the timeout issue. Might be a stale session bug or something?

**Comment by LeonardSSH** [comment]
@Hyperclaw79 Might be, who knows 🙄

**Comment by AnggaaIs** [comment]
> Hi, i have problem with rpc every time i open vsc it don't start,to fix it i reinstall this excention

Yeah, I also experienced the same thing.
