### ISSUE TITLE
Objective-C Icon broken

### ISSUE THREAD

**Issue by Davoleo** [leonardssh/vscord#59]
For some reasons Objective-C Icon doesn't show correctly despite existing in [in the project](https://github.com/LeonardSSH/vscord/blob/main/assets/icons/objc.png)
Maybe it's a naming issue?

![Screenshot 2022-04-16 at 10 43 15](https://user-images.githubusercontent.com/24458276/163669370-2c827c79-8e39-4e0f-adf0-863f8d76a112.png)

**Comment by Alepacho** [comment]
same thing
![telegram-cloud-photo-size-2-5443035934695210129-x](https://user-images.githubusercontent.com/22509949/183353266-7f534065-96c4-4c82-babc-924afc28a474.jpg)

**Comment by Alepacho** [comment]
thx

**Comment by xhayper** [comment]
np
