### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by ZyrexFX** [LeonardSSH/vscord#6]
Can i activate the timestamp using the vscode command?

**Comment by LeonardSSH** [comment]
Yeah, you cand do this by checking: 
![box](https://stepbro.please-fuck.me/u8D9un.png)
From the extension settings, or just set it directly in the settings file.
```json
"VSCord.workspaceElapsedTime": true
```

**Comment by ZyrexFX** [comment]
Ok, thanks

**Comment by LeonardSSH** [comment]
No problem. Have a nice day!
