### ISSUE TITLE
Icon for .moon extension

### ISSUE THREAD

**Issue by catswimmer** [leonardssh/vscord#60]
Hey!
I often code MoonScript, and I was wondering if you could add icons for it to RPC?
Currently how it looks:
![image](https://user-images.githubusercontent.com/99511627/164472872-06e9f1ff-a9ea-4556-8598-90f51c3932cd.png)

It would be amazing if you added it.

**Comment by LeonardSSH** [comment]
Will be added soon™️.

**Comment by nick22985** [comment]
https://github.com/leonardssh/vscord/commit/43e6d1069e09
Moon script needs a icon
