### ISSUE TITLE
Certain file types not supported || crashes because of memory leaks

### ISSUE THREAD

**Issue by ProFireDev** [LeonardSSH/vscord#7]
does not support .md files or any other type of GitHub related thing. also it will crash and stop working after about a day and a half before needing to be restarted due to the aforementioned memory leaks.

**Comment by LeonardSSH** [comment]
The problem should be fixed in the newly released version, please upgrade to the extension and let me know if the problem is fixed.

**Comment by ProFireDev** [comment]
the issue has been fixed as of the latest version, thanks!
