### ISSUE TITLE
What's next?

### ISSUE THREAD

**Issue by leonardssh** [leonardssh/vscord#83]
Many of you have probably seen that I've restarted the maintenance of the extension as time permits. That said, I want to take the extension to another level. I want it to be the most up-to-date extension of its kind on the market. 😎

Thanks to @xhayper, we now have a better & up-to-date version of the [discord-rpc](https://github.com/xhayper/discord-rpc). Therefore new versions of the extension should fix all reported issues (I hope 😅)

Below I leave a list of everything that should have and fix version v5.

### 🚀 Improvements
- [ ] Better approach to the service processing the data (https://github.com/leonardssh/vscord/pull/35#issuecomment-968287185)
- [ ] Wiki page?
- [x] New README?

### 🪲 Bugs
- [x] https://github.com/leonardssh/vscord/issues/75
- [x] https://github.com/leonardssh/vscord/issues/65
- [x] https://github.com/leonardssh/vscord/issues/59
- [x] https://github.com/leonardssh/vscord/issues/57
- [x] https://github.com/leonardssh/vscord/issues/36
- [x] https://github.com/leonardssh/vscord/issues/27
- [x] https://github.com/leonardssh/vscord/issues/26

### ⭐ Requests
- [ ] https://github.com/leonardssh/vscord/issues/71
- [x] https://github.com/leonardssh/vscord/issues/70
- [x] https://github.com/leonardssh/vscord/issues/63
- [ ] https://github.com/leonardssh/vscord/issues/60

> Each of you is welcome to help with these tasks! 🥰

**Comment by Sominemo** [comment]
Hello,

Maybe it would make sense to make a 4.x release without waiting for a 5.0 since it already has a lot of important improvements waiting.

**Comment by AYMENJD** [comment]
Suggestion: Manually specify discord client token instead of having a running instance of Discord desktop.

**Comment by xhayper** [comment]
> Suggestion: Manually specify discord client token instead of having a running instance of Discord desktop.
> 
> For example: if i don't have discord client on my machine.

that could be against the TOS for selfbot.
