### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Tom-Sumner** [leonardssh/vscord#84]
Extension says connected but nothing happens to my discord presence.

Tried reinstalling and restarting Discord and VS-Code

Any help will be appreciated.

**Comment by TheAlphaReturns** [comment]
create a new terminal and then go to the output tab. click the dropdown and click RPC. what does it say?

**Comment by Tom-Sumner** [comment]
I got nothing however when I ran "Discord Rich Presence: Reconnect Discord Presence to Discord Gateway" i got this 
![image](https://user-images.githubusercontent.com/85069468/186848081-5edb64a4-5d9d-4232-a8ed-66e118b4044b.png)

**Comment by Kiirx** [comment]
happening to me also, the extension is useless now

**Comment by TheAlphaReturns** [comment]
The rpc.enable: command not found error happens when you have installed the extension and have not properly restarted vscode. Try reinstalling the extension, then close vscode and kill all its processes. Open vscode and make sure discord is running before you do so.

**Comment by Tom-Sumner** [comment]
This doesnt work ^

**Comment by Tom-Sumner** [comment]
Im now getting this.

![image](https://user-images.githubusercontent.com/85069468/188280444-3675b3c7-0054-4088-b6dd-9dfd6e7cda66.png)

This ID is not my discord id, and it isnt the default id.

**Comment by TheAlphaReturns** [comment]
No, it's your discord client id (the is separate from your user id)

**Comment by Tom-Sumner** [comment]
> 

Im on windows. Not Linux

**Comment by Tom-Sumner** [comment]
No more errors however discord still is not showing anything.

**Comment by Tom-Sumner** [comment]
OK its working now, for some reason my discord settings were not allowing it to show.
