### ISSUE TITLE
Image at Voice chat hover.

### ISSUE THREAD

**Issue by bendeguzbagi** [leonardssh/vscord#89]
If you hover the cursor to a voice chat you in, you got this result: [imgur](https://imgur.com/wlguRVZ)

**Comment by leonardssh** [comment]
Seems to be a issue with Discord, not my extension.

![image](https://user-images.githubusercontent.com/35312043/189132323-0d7cdf2a-9f9b-4812-afc1-2200c2ee1388.png)
![image](https://user-images.githubusercontent.com/35312043/189132338-d7ad383f-4c76-46a2-899d-05286d679bd2.png)

**Comment by bendeguzbagi** [comment]
Thanks for the fast answer!

**Comment by leonardssh** [comment]
No problem, I'll close this issue since it has nothing to do with my extension.
