### ISSUE TITLE
rpc.buttonIncactiveLabel for private repos

### ISSUE THREAD

**Issue by nick22985** [leonardssh/vscord#97]
Make it so the discord button in activity detects if a GitHub repo is private and then make it display different text / the buttonInactiveLabel & buttonInactiveUrl

**Comment by xhayper** [comment]
Some reference (for my future self):
https://docs.github.com/en/rest/repos/repos#get-a-repository

**Comment by xhayper** [comment]
we have a problem, and that is we have multiple git provider, gitlab, github and some scary third party git provider, if we were to add support for this, it gonna take a lot of effort and code
